# -*- coding: utf-8 -*-
import os

full_dict = {
    # Main Navigation & Window
    "Whiteout Survival Bot": "无尽冬日自动化助手",
    "Whiteout Survival Bot v2.1.0": "无尽冬日自动化助手 v2.1.0",
    "Loaded profile": "当前加载账号",
    "Search activities...": "搜索功能与任务...",
    "Uptime:": "运行时间:",
    "Uptime": "运行时间",
    "Uptime: 00:00:00": "运行时间: 00:00:00",
    "Version: 2.1.0": "版本: 2.1.0",
    "Version:": "版本:",
    "Like the bot? Buy me a Coffee": "喜欢这个软件？赞助开发者",
    "Like the bot? Buy me a Coffee ☕": "喜欢这个软件？赞助开发者",
    "Having problems? Join our Discord": "遇到了问题？加入 Discord 社区",
    "Close": "关闭",
    "Minimize": "最小化",
    "Maximize": "最大化",

    # Main Tabs
    "Logs": "运行日志",
    "Profiles": "账号配置",
    "Tasks": "任务列表",
    "Custom Tasks": "自定义任务",
    "Emulators": "模拟器配置",
    "Telegram": "Telegram 提醒设置",

    # Buttons & Controls
    "Start Bot": "启动机器人",
    "Stop": "停止运行",
    "Starting...": "启动中...",
    "Stopping...": "停止中...",
    "Pause": "暂停",
    "Pause All Q...": "暂停队列",
    "Pause all queues": "暂停所有队列",
    "Pause current queue": "暂停当前队列",
    "Clear Logs": "清空日志",
    "Open Logs Folder": "打开日志目录",
    "DEBUG": "调试日志",
    "Save Configuration": "保存配置",
    "Apply settings": "应用设置",
    "Fetch Codes": "获取礼包码",
    "Copy All": "复制全部",
    "Copy Settings to Profiles": "复制配置到其他账号",
    "Clear": "清空",
    "Clear All": "清空全部",
    "Reset Statistics": "重置统计数据",
    "Test Connection": "测试连接",
    "Add Profile": "添加账号配置",
    "New Profile": "新建账号",
    "+ New Profile": "新建账号配置",
    "Bulk Update": "批量更新",
    "Save": "保存",
    "Cancel": "取消",
    "Back": "返回",
    "Run": "运行",
    "Running": "运行中",
    "Scheduled": "已计划",
    "Execute": "执行",
    "Execute All": "全部执行",
    "Execute immediately": "立即执行",
    "Capture": "截图抓取",
    "Export": "导出",
    "Refresh": "刷新",
    "Select all": "全选",
    "Choose Action": "选择操作",
    "Choose Profile...": "选择账号...",

    # Log Table
    "TIMESTAMP": "时间戳",
    "LEVEL": "级别",
    "MESSAGE": "日志内容",
    "PROFILE": "账号配置",
    "TASK": "任务名称",
    "Settings": "账号配置",
    "Filter log entries...": "搜索过滤日志条目...",
    "All profiles": "全部账号配置",
    "All levels": "全部日志级别",

    # EmuConfig (System Settings)
    "Instance Settings": "多开实例全局设置",
    "Game Settings": "游戏参数设置",
    "ACTIVE": "启用状态",
    "EMULATOR": "模拟器名称",
    "PATH": "安装路径",
    "ACTION": "操作选项",
    "ACTIONS": "操作选项",
    "Idle Behavior": "空闲处理行为",
    "Close Emulator": "关闭模拟器",
    "Do Nothing": "不作处理",
    "Max Concurrent Instances": "最大同时运行多开数",
    "Max Idle Time (minutes)": "最大空闲等待时间 (分钟)",
    "Limit Profile Active Time": "限制账号单次挂机时长",
    "min": "分钟",
    "Stop Behavior": "停止策略",
    "Auto start all Profiles after module load": "模块加载完成后自动启动所有账号",
    "Stop Behavior Telegram": "Telegram 停止策略",
    "Delay:": "延迟:",
    "min. Mode:": "分钟  模式:",
    "Continuous": "连续模式",

    # Tasks Sidebar & Categories
    "Control": "控制面板",
    "Config": "系统设置",
    "Dummy Task": "示例测试任务",
    "City Upgrades": "城市建筑升级",
    "City Events": "城市事件处理",
    "Extra City Events": "额外城市事件",
    "Rally": "极地恶魔集结",
    "Shop": "游商与商店",
    "Gather": "野外资源采集",
    "Intel": "雷达情报任务",
    "Alliance": "联盟事务管理",
    "Alliance Championship": "联盟争霸赛",
    "Alliance Shop": "联盟商店",
    "Alliance Mobilization": "联盟动员大奖赛",
    "Bear Trap": "熊陷阱活动",
    "Beast Hunting": "野外野兽猎杀",
    "Fishing Tournament": "钓鱼大赛",
    "Training": "部队士兵训练",
    "Research": "科技研究",
    "Pets": "宠物探险宝藏",
    "Events": "限时活动与福利",
    "Experts": "专家委派管理",
    "Chief Order": "领主指令发布",
    "Get Giftcodes": "领取礼包码",
    "Debugging": "图像调试工具",
    "Task Builder": "任务流程构建器",
    "Skip Tutorial": "跳过新手引导",
    "Character": "角色属性数据",
    "Statistics": "全盘数据统计",

    # Profile Manager
    "Profile Name": "账号名称",
    "Emulator": "模拟器序号",
    "Priority": "优先级",
    "Status": "当前状态",
    "Furnace Level": "熔炉等级",
    "Stamina": "体力值",
    "Delete": "删除",
    "Enabled": "启用",

    # Detailed Task Options & Labels
    "Upgrade Furnace Priority": "优先升级熔炉",
    "Auto Upgrade Buildings": "自动升级建筑",
    "Max Building Level": "最高升级等级限制",
    "Prioritise Furnace": "优先升级熔炉",
    "Reserve training/research for required upgrades": "为建筑升级保留训练与科技资源",
    "Configure automated building upgrades safely": "安全配置自动化建筑升级策略",
    "Claim Free Chests": "自动领取免费宝箱",
    "City Officer Assignments": "自动委派城市官职",
    "Claim Mail Rewards": "自动领取邮件奖励",
    "Claim Intel (Agnes)": "自动领取情报奖励 (Agnes)",
    "Claim Loyalty Tag (Romulus)": "自动领取忠诚标签 (Romulus)",
    "Claim Troops (Romulus)": "自动领取预备役 (Romulus)",
    "Claim daily missions": "自动领取每日任务奖励",
    "Claim daily vip rewards": "自动领取每日 VIP 奖励",
    "Claim exploration chest": "自动领取挂机探索宝箱",
    "Claim honor chest": "自动领取荣誉宝箱",
    "Claim storehouse chests + stamina": "自动领取仓库宝箱与体力",
    "Claim crystal lab FC": "自动领取火晶实验室火晶",
    "Claim war academy crystal shards": "自动领取战争学院火晶碎片",
    "Claim daily 50% RFC": "自动领取每日 50% 折扣火晶",
    "Accept new survivors": "自动接受新幸存者",
    "Appoint Minister of Education": "自动委派教育部长",
    "Auto Join Bear Trap": "自动参加熊陷阱",
    "March Count": "出征队列数量",
    "Hero Preset": "出征英雄预设",
    "Number of Marches": "出征队列数量",
    "Trap Target": "陷阱目标",
    "Enable Bear Trap": "开启熊陷阱自动化",
    "Auto Hunt Beasts": "自动猎杀野兽",
    "Stamina Threshold": "体力保留阈值",
    "Target Level": "目标野兽等级",
    "Beast Level": "野兽等级",
    "Enable Beast Hunting": "开启野兽猎杀",
    "Use stamina items when needed": "体力不足时自动使用体力补充道具",
    "Auto Rally Polar Terror": "自动发起/加入极地恶魔",
    "Rally Duration": "集结等待时间 (分钟)",
    "Enable Polar Terror Hunting": "开启极地恶魔集结",
    "Stamina Reserve": "保留体力值",
    "Rally Autojoin": "自动加入他人集结",
    "Call Own Rally": "发起自己的集结",
    "Gather Resources": "野外资源采集",
    "Meat": "生肉",
    "Wood": "木材",
    "Coal": "煤炭",
    "Iron": "铁矿",
    "Speed Boost": "使用采集加速道具",
    "Only Full Resources": "仅采集满级资源点",
    "Downgrade Level": "自动降低资源点等级",
    "Downgrade level if no node is found": "未找到指定等级资源点时自动降低等级",
    "Gather Speed Boost": "采集加速",
    "Gathering Resource": "目标采集资源种类",
    "Complete Intel Missions": "自动完成情报任务",
    "Radar Auto Refresh": "雷达自动刷新",
    "Enable Intel Runs": "开启情报任务",
    "Intel Categories": "情报任务类型",
    "Use Smart Intel Processing": "智能挑选完成情报",
    "Pet Adventure": "宠物冒险探险",
    "Pet Treasure": "宠物宝藏挖掘",
    "Auto Feed Pets": "自动喂养宠物",
    "Enable Pet Management": "开启宠物管理",
    "Active Pets": "激活宠物",
    "Pet Automation": "宠物自动化",
    "Train Infantry": "训练步兵",
    "Train Marksman": "训练射手",
    "Train Lancer": "训练矛兵",
    "Auto Promote": "自动晋升低级士兵",
    "Enable Training": "开启士兵训练",
    "Prioritize Troop Promotion": "优先晋升低等级士兵",
    "All Troops": "全部兵种",
    "Research Tech": "研发学院科技",
    "Priority Category": "优先科技分类",
    "Enable Research": "开启科技研究",
    "Research Priorities": "科技研发优先顺序",
    "Automates research technology in your city": "自动化研发您城市中的科技项目",
    "Gift Codes": "游戏礼包码",
    "Click 'Fetch Codes' to load gift codes.": "点击“获取礼包码”从服务器检索最新的可用兑换码。",
    "No gift codes loaded yet.": "尚未加载礼包码，请点击上方的“获取礼包码”按钮。",
    "Telegram": "Telegram 消息提醒",
    "Enable Telegram Remote Control": "开启 Telegram 远程控制",
    "Bot Token": "Telegram Bot Token",
    "Allowed Chat ID": "授权 Chat ID",
    "Show token": "显示 Token 明文",
    "Paste your token from @BotFather": "请在此粘贴从 @BotFather 获取的机器令牌",
    "Commands Reference": "Telegram 指令帮助",
    "Activity Counters": "全盘运行数据统计",
    "Character Information": "角色详细属性与参数",
    "Character Creation": "自动创建角色新号",
    "Skip Tutorial Settings": "跳过新手教程设置",
    "This task will attempt to skip the initial tutorial. Use with caution on new accounts.": "该任务将尝试跳过游戏开局新手教程，新账号请谨慎使用。",
    "Alliance Shop Automation": "自动购买联盟商店道具",
    "Enable Alliance Shop": "开启联盟商店自动化",
    "Min Coins": "保留最低联盟币数量",
    "Min Coins to Activate": "触发购买最低联盟币要求",
    "Purchase Priorities": "购买优先级顺序",
    "Mystery Shop": "神秘黑市商店",
    "Enable Mystery Shop": "开启神秘商店自动化",
    "Use Gems": "允许使用钻石购买",
    "Use Gems for Accept": "允许使用钻石刷新/接受",
    "Nomadic Merchant": "游商交易",
    "Configure purchases from the Nomadic Merchant shop": "配置游商打折资源的自动购买策略",
    "Buy Package": "购买直购礼包",
    "Buy VIP points": "购买 VIP 经验点数",
    "Buy resources": "购买资源道具",
    "Language": "界面语言",
    "Simplified Chinese": "简体中文",
    "English": "English",

    # Status & Dialogs
    "Success": "操作成功",
    "Error": "发生错误",
    "Warning": "警告",
    "Information": "提示信息",
    "Confirm": "确认",
    "Are you sure?": "确定要执行此操作吗？",
    "Status: 🔴 Stopped": "当前状态: 🔴 已停止运行",
    "Status: 🟢 Running": "当前状态: 🟢 正常运行中"
}

# Read missing keys file if exists and auto-add missing
missing_file = r"tools\missing_keys.txt"
if os.path.exists(missing_file):
    with open(missing_file, "r", encoding="utf-8") as f:
        for line in f:
            k = line.strip()
            if k and not k.startswith("Total missing:") and k not in full_dict:
                # Add auto readable fallback for any unlisted technical phrases
                full_dict[k] = k

out_properties = r"fg-app\src\main\resources\i18n\messages_zh_CN.properties"
with open(out_properties, "w", encoding="utf-8") as f:
    f.write("# Frostguard Full Chinese Dictionary\n\n")
    for k, v in sorted(full_dict.items()):
        f.write(f"{k}={v}\n")

print(f"Successfully generated {len(full_dict)} dictionary entries in {out_properties}")
