# -*- coding: utf-8 -*-
import os

engine_log_translations = {
    "10 VIP XP": "10 VIP 经验",
    "100 VIP XP": "100 VIP 经验",
    "A free reward has been claimed.": "已成功领取一项免费奖励。",
    "A task is already running - only one task can run at a time": "当前已有任务正在运行 - 一次只能运行一个任务",
    "ADB Slot Acquired": "已获取 ADB 连接槽位",
    "ADB bridge restarted": "ADB 连接桥已重新启动",
    "ADB error:": "ADB 连接错误:",
    "ADB health check failed even after recovery attempts.": "ADB 健康检查失败，多次恢复尝试均未成功。",
    "ADB health check passed. Proceeding with emulator restart.": "ADB 健康检查通过，正在重启模拟器进程。",
    "ADB link broken": "ADB 连接中断",
    "Accepting task": "正在接受任务",
    "Accepting...": "正在接受中...",
    "Account identifier must not be null": "账号标识符不能为空",
    "Activating checkbox": "正在勾选框",
    "Activating pets...": "正在激活宠物技能...",
    "Activation time": "激活运行时间",
    "Active": "已激活",
    "Active deployment detected": "已检测到正在出征的队列",
    "Added:": "已添加:",
    "Advanced": "高级设置",
    "Advanced Teleport": "高级迁城道具",
    "After": "之后",
    "Agnes": "Agnes (情报女官)",
    "Agnes icon found - claiming intel": "找到 Agnes 图标 - 正在领取情报奖励",
    "All": "全部",
    "All button activation methods failed. Cannot start automation.": "所有启动按钮激活尝试均失败，无法开启挂机自动化。",
    "All gather slots filled": "所有采集队列均已派满",
    "All gather troops recalled. Proceeding with intel processing.": "所有采集部队已召回，开始处理情报任务。",
    "All march queues used.": "所有出征队列均已满载。",
    "Alliance Shop Purchases": "联盟商店购买项目",
    "Alliance Shop enabled. Inspecting current coins.": "联盟商店已启用，正在检查当前联盟币数量。",
    "Alliance Shop is disabled. Skipping shop check.": "联盟商店未启用，跳过检查。",
    "Alliance Triumph": "联盟胜利勋章",
    "Alliance treasure claimed successfully": "联盟宝藏已成功领取",
    "Already active — done": "已经是激活状态 — 完成",
    "Already on Intel": "当前已在情报界面",
    "An error occurred during the Labyrinth task:": "迷宫任务执行过程中发生错误:",
    "An error occurred during the Mercenary Event task:": "雇佣兵任务执行过程中发生错误:",
    "Analyzing queue": "正在分析任务队列",
    "Any": "任意",
    "App com.gof.global is not in foreground": "游戏应用 com.gof.global 当前未在前台显示",
    "App not running": "游戏应用当前未运行",
    "Application com.gof.global launched": "游戏应用 com.gof.global 已成功启动",
    "Application launched": "应用已成功启动",
    "Apply profile settings": "应用当前账号配置参数",
    "Applying for ministry appointment": "正在申请官职委派",
    "Arena Battles Lost": "竞技场战败次数",
    "Arena Battles Won": "竞技场胜场次数",
    "Arena Gems Spent": "竞技场消耗钻石",
    "Arena Refreshes": "竞技场刷新次数",
    "Arena run finished after using available eligible attempts.": "竞技场尝试次数已用完，挂机结束。",
    "Arena score:": "当前竞技场积分:",
    "Assigning survivors to available building slots.": "正在安排幸存者至空闲建筑工作岗位。",
    "Attack target icon should match the attack row:": "攻击目标图标应匹配对应行:",
    "Attacking mercenary.": "正在攻击野外雇佣兵。",
    "Attempting Alliance Help tap": "尝试点击帮助联盟成员",
    "Attempting promotion for:": "正在尝试晋升士兵:",
    "Attempting to buy weekly free scroll": "尝试购买每周免费卷轴",
    "Attempting to send left truck.": "尝试派出左路货车。",
    "Attempting to send right truck.": "尝试派出右路货车。",
    "Auto": "自动",
    "Auto-Start-Thread": "自动启动线程",
    "Auto-join activation command sent": "自动加入集结指令已发送",
    "Auto-start: ✅ Registered": "开机自启: ✅ 已注册",
    "Automation sequence started successfully": "挂机自动化流程已成功启动",
    "Avoid profile alliance": "避开账号所属联盟",
    "Avoid profile server": "避开账号所属区服",
    "Back Button": "返回按钮",
    "Bank Transaction Completed": "理财金库交易已完成",
    "Bank Deposit": "理财存款",
    "Bank Withdrawal": "理财取款",
    "Bank is enabled. Inspecting current gems.": "理财金库已启用，正在检查钻石储备。",
    "Bank is disabled. Skipping.": "理财金库未启用，跳过。",
    "Beast Hunting Routine Started": "野兽猎杀自动化已开始",
    "Beast target level:": "目标野兽等级:",
    "Beast target found at coordinate:": "在坐标处找到目标野兽:",
    "Beast hunt march dispatched": "野兽猎杀出征队列已派出",
    "Bear Trap Routine Started": "熊陷阱自动化已开始",
    "Bear Trap is inactive. Next trap window at:": "熊陷阱未开启，下次陷阱时间:",
    "Bear Trap prep window active. Preparing marches.": "熊陷阱准备时间开启，正在组建队列。",
    "Bear Trap rally called": "熊陷阱集结已成功发起",
    "Building Upgrades Routine Started": "建筑升级自动化已开始",
    "Building upgrade started:": "建筑升级已启动:",
    "Building upgrade completed:": "建筑升级已完成:",
    "Building queue full. Waiting for free queue.": "建筑队列已满，等待队列空闲。",
    "Character Creation Routine Started": "自动建号流程已开始",
    "Character created successfully:": "新角色已成功创建:",
    "Character switch started to profile:": "开始切换角色至账号:",
    "Character switch completed for profile:": "角色切换成功:",
    "City Events Routine Started": "城市内部事件自动化已开始",
    "City event completed:": "城市内部事件处理完成:",
    "Claiming daily missions...": "正在领取每日任务奖励...",
    "Daily missions claimed successfully": "每日任务奖励已成功领取",
    "Claiming mail rewards...": "正在自动领取邮件奖励...",
    "Mail rewards claimed successfully": "邮件奖励已成功领取",
    "Claiming VIP daily rewards...": "正在领取 VIP 每日奖励...",
    "VIP rewards claimed": "VIP 每日奖励已成功领取",
    "Claiming exploration rewards...": "正在领取挂机探索宝箱...",
    "Exploration rewards claimed": "挂机探索宝箱已成功领取",
    "Connecting to ADB device...": "正在尝试连接 ADB 模拟器设备...",
    "ADB Connected successfully": "ADB 模拟器连接成功",
    "ADB Connection failed": "ADB 模拟器连接失败",
    "Custom task execution started:": "自定义任务开始执行:",
    "Custom task finished successfully:": "自定义任务执行成功:",
    "Expert skill upgrade started:": "专家技能升级已开始:",
    "Expert skill upgrade completed:": "专家技能升级已完成:",
    "Fishing minigame started": "钓鱼大赛小游戏已开始",
    "Fishing minigame finished": "钓鱼大赛小游戏已结束",
    "Gathering march dispatched for resource:": "资源采集队列已成功派出:",
    "Gathering completed for resource:": "资源采集完成:",
    "Gathering node not found. Trying lower level.": "未找到资源点，尝试降低目标等级。",
    "Hero Presets": "英雄出征预设",
    "Intel mission started:": "雷达情报任务已开始:",
    "Intel mission finished:": "雷达情报任务已完成:",
    "Intel radar refreshed": "雷达情报已成功自动刷新",
    "Journey of Light event routine active": "逐光之旅活动自动化处理中",
    "Mercenary hunting march dispatched": "雇佣兵猎杀队列已派出",
    "Mercenary event completed": "雇佣兵活动处理完毕",
    "Mystery Shop opened": "神秘黑市商店已打开",
    "Mystery Shop purchase completed:": "神秘黑市购买成功:",
    "Myriad Bazaar collection completed": "万象集市免费奖励领取完毕",
    "Nomadic Merchant opened": "游商小贩打折商店已打开",
    "Nomadic Merchant purchase completed:": "游商打折商品购买成功:",
    "Pet skill activated:": "宠物技能已成功释放:",
    "Pet fed successfully": "宠物喂养成功",
    "Pet adventure started": "宠物冒险探险已开启",
    "Pet treasure dug": "宠物宝藏已挖掘",
    "Polar Terror rally joined": "极地恶魔集结已成功加入",
    "Polar Terror rally called": "极地恶魔集结已成功发起",
    "Polar Terror routine completed": "极地恶魔挂机完成",
    "Research started:": "科技研发已开始:",
    "Research completed:": "科技研发已完成:",
    "Research queue busy": "科技研发队列繁忙",
    "Skip tutorial routine running...": "正在自动跳过新手引导...",
    "Skip tutorial finished": "新手引导已成功跳过",
    "Troop training started:": "部队士兵训练已开始:",
    "Troop training finished:": "部队士兵训练已完成:",
    "Troop promotion started:": "士兵晋升已开始:",
    "Troop promotion finished:": "士兵晋升已完成:",
    "Tundra Truck dispatched:": "苔原货车已成功派货:",
    "Tundra Truck refreshed": "苔原货车已成功刷新"
}

properties_file = r"fg-app\src\main\resources\i18n\messages_zh_CN.properties"

existing = {}
with open(properties_file, "r", encoding="utf-8") as f:
    for line in f:
        if "=" in line and not line.strip().startswith("#"):
            k, v = line.split("=", 1)
            existing[k.strip()] = v.strip()

existing.update(engine_log_translations)

with open(properties_file, "w", encoding="utf-8") as f:
    f.write("# Frostguard Complete Chinese Dictionary with Engine Log Phrases\n\n")
    for k, v in sorted(existing.items()):
        f.write(f"{k}={v}\n")

print(f"Updated properties file with {len(existing)} entries")
